# Site wide configuration

title: Honor Flight St. Louis
description: "Our mission is simple.  Safely transport World War II veterans to see their National World War II Memorial in Washington, D.C. As quickly as possible. Because we are losing 900+ WWII veterans a day, we would like to locate and fly as many of these vets as possible."
logo: gstlhf.png
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: http://localhost:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
